### PR TITLE
Introduce pointer aliasing

### PR DESCRIPTION
**Pull request by twocs**
Optimize following example of p_popcount.c

Signed-off-by: Tom Anderson <github@tom-anderson.com>

### CODE REVIEW

**Comment by olajep** [comment]
Can't we just do this with `restrict` in the function prototype?

**Comment by GBuella** [comment]
I looked at the commit, and have no idea what it would have to do with pointer aliasing. Basically, the same thing is happening in p_ftoi, only with more local variables. Overlapping data yields the same result, as the original version. Actually, clang generated larger code on my computer.
But, I tried the code with restrict added, clang generated smaller code, an lower code size is a design gole according to README.md.
Adding restrict does also solve any questions about pointer aliasing here.

**Comment by GBuella** [comment]
Now I suspect this commit is due to a typo,
The commit message says "Optimize following example of p_popcount.c",

Perhaps there was
git add p_ftoi.c
instead of
git add p_popcount.c
before commiting??

**Comment by twocs** [comment]
Andreas mentioned "An example of an optimized function." and pointed to p_popcount.c
(https://www.parallella.org/2015/06/02/write-one-c-function-and-get-a-free-computer)

The main goal here is to change *(a + i) by calling it *pa, which will reduce the number of times that the calculation (a + i) is performed.

Isn't the aliasing is also useful for when the code is run in parallel?

**Pull request closed without merging**
