### PR TITLE
Makes sqrt more accurate by adding an extra iteration

### PR DESCRIPTION
**Pull request by HenryJia**

### CODE REVIEW

**Comment by warrenm** [comment]
Just curious, since very similar code exists in p_invsqrt_f32, can you quantify the increase in accuracy with this change?

**Comment by HenryJia** [comment]
@warrenm Not much, but when I was using the original code for square rooting for my code for the standard deviation function, I got quite an inaccurate result.

The original square root code got me about 0.9 when I tried and calculate the standard deviation of {1, 2, 3} as opposed to the correct result of 1 which I obtained with 3 iterations

Also, the code does work using Newton's method I believe, which converges quite significantly more accurately with each iterations.

**Comment by WesleyCeraso** [comment]
There is no guarantee that any function will converge in 2 3 or n iterations. There should be a loop with a stop criteria, maybe the value changed by less then 1% from the last iteration.

**Comment by HenryJia** [comment]
Hmmm, the question is should you make it use the SSE instruction set?

Should PAL be compatible with machines that don't have SSE?

**Comment by WesleyCeraso** [comment]
I think we are going to have ifdefs or different files for each architecture. I don't know for sure.
The performance gain that sse and others instruction sets have is big enough to force us to use them.

**Comment by HenryJia** [comment]
Alright, I think I'll start work on that. I'll add an ifndef into the headers for the SSE instruction set and optimise the functions to use that. I think I'll do this on separate branch and PR though as this isn't something that's exclusive to sqrt.

**Comment by HenryJia** [comment]
Although regarding looping until convergence, could that possibly result in the function taking far too long to execute? I think there should be a limit on iterations but stop iterating if it already converges before it reaches that limit.

**Comment by WesleyCeraso** [comment]
@HenryJia I think it depends on the purpose of the library. If you look the original implementation of the Fast Inverse Square Root you`ll see they use one/two newton iteration because we wouln`d be able to notice the diference in a game.
As you tried to apply the function to statistics, the precision was not enough for you, but 3 iterations did it.
However, if you are trying to simulate some physical fenomena and want to publish a paper, you need the best precision possible, maybe ten iterations won`t be enought.
I think it`s up to @aolofsson to define which way we should follow.

**Pull request merged**
