### PR TITLE
math: Implement a basic "map" function for unary functions

### PR DESCRIPTION
**Pull request by eliteraspberries**
Looking at the excellent work of @jar in the image processing algorithms, I wanted to do the same type of partial loop unrolling in the basic math functions. Working on four values at a time lets the compiler produce more vector arithmetic instructions.

This is a basic implementation of a "map" function, `p_map_unary`. It basically replaces a for loop. Its first argument is a pointer to a "pure" function that has a single argument. The other arguments are the input, output arrays, and array size, respectively.

I used it in some functions and it makes them larger but faster. Note that you should use the compiler flag `-march=native` to get the benefits of SIMD. (About 20% on x86.)

### CODE REVIEW

**Comment by lchamon** [comment]
Could you explain the rationale behind your inline `_function_name` implementations? I'm sorry if the benefits aren't clear to me... I understand that it avoids some repetition (e.g., `asin`/`acos`), but most of the time `function_name` just calls `_function_name` directly. In my opinion this obscures the implementations and adds unnecessary header files.

Also, loop unrolling is a great idea, but you should do it directly instead of using an indirect function. When a function is declared as `static inline`, calling it through a pointer forces the compiler to provide assembler code to it (to get its address) and prevents it from being integrated (this is the behavior of GCC). Hence, you end up adding "regular" function calls to your implementation.

**Comment by eliteraspberries** [comment]
The main benefit is that the compiler does instruction pipelining.

Taking the address of an inline function doesn't make it not inlined. GCC and Clang both inline it. Look at the assembler output.

**Comment by lchamon** [comment]
*On unrolling:*
Sorry, I'm very biased toward GCC. I've never used Clang. GCC inline is a little mess: it does different things depending on whether the program is compiled in C89 or C99. Unrolling directly in the functions is safer e not much worst in terms of clutter (in my opinion). BTW, GCC does not guarantee that indirect calls to functions (e.g., through pointers) are inlined or raise errors with `always_inline`. Did you check the assembly?

*On hidden implementation:*
Indeed loop unrolling improves pipelining. I don't see how stashing the implementation in a `_function()` would. I had to open 4 files to look at your current implementation of `asin` (`p_asin.c`, `p_asin.h`, `p_sqrt.h`, and `pal_math.h`). Since using `-O3` with GCC will choose inline small functions if the gains are worth it (independently of they being declared as `inline`), I still cannot see the advantage.

**Comment by eliteraspberries** [comment]
Yeah GCC behaves differently depending on the options. For example `-O3` turns on `-finline-functions`. I used `-O3 -ffast-math`. I double checked that with the `always_inline` attribute, everything is inlined properly.

Reusing code is a good idea. If eight functions share the same code, it should be its own function. The asin implementation requires sqrt -- to improve sqrt, edit one file, not two. To improve exp, edit one file, not four. And so on.

**Comment by lchamon** [comment]
Awesome then!

*As for the other question:* I get code reusing. I'm just wondering why all the indirect implementations if you can just implement `p_asin` directly, call `p_sqrt` directly, and let the compiler do the inlining himself. Same for `p_acos`: just call `p_asin`. GCC will inline all small functions (declared with inline or not) with `-O2`. With `-O3`, it considers every single functions for inlining (if you feel it is being conservative, you can increase `-finline-limit` to inline more functions at the cost of code size).

You get the exact same result with more readable code. There is no need for `inline _function()` and more header files.

**Comment by eliteraspberries** [comment]
I just did some more benchmarks. It looks like the compiler can do just as good optimization with the right flags (`-march=native -O3 -ffast-math -finline-functions`). Oh well, it was fun to try. :)

**Comment by lchamon** [comment]
Was that for the code reusing `static inline _function`s or the loop unrolling? Can you talk a little about the benchmarks/results? Do you need `-finline-functions` (`-O3` doesn't do that)?

Sorry for all the questions, but you really got me curious! Just trying to get your experience. I'm working on the DSP library and it would be nice to have an idea of what work and what doesn't. Could also help with the compiling flags for PAL...

**Pull request closed without merging**
