### PR TITLE
Implement fastest pow() function base on the work of Harrison Ainsworth

### PR DESCRIPTION
**Pull request by nplanel**
With a precision table set to 11 bits (8KB table), mean error is < 0.01%, and max error is < 0.02%.
On my computer i7-2630QM @ 2.0GHz I observe the code running 11 times faster than the glibc pow().

This implementation is based on work of Harrison Ainsworth.
http://www.hxa.name/articles/content/fast-pow-adjustable_hxa7241_2007.html

### CODE REVIEW

**Comment by nplanel** [comment]
make distcheck failed as mentioned in my patch there are error (less than 0.02 %)

Could you change the gold test to accept these margin errors of the test should pass even if the function is 11 times faster ?

**Comment by aolofsson** [comment]
@olajep Please change the golden data for now. Would like to see this function in there.

**Comment by nplanel** [comment]
@olajep I updated the golden values and the reference test too.

**Comment by aolofsson** [comment]
Please sign off commits.

**Comment by nplanel** [comment]
done

**Comment by nplanel** [comment]
@aolofsson @olajep : Do you have any issue to merge this pull ?

**Comment by olajep** [comment]
@aolofsson 
You're ok with that the mantissa table is 8192 bytes?

https://parallella.github.io/pal-stats/pr-153/codesize.arm.html

**Pull request merged**
