### PR TITLE
Fixed incorrect implmentation of image/conv2 and dsp/conv, hardwired network for p_median3x3_f32 

### PR DESCRIPTION
**Pull request by ebadi**
The array is sorted but not used at all, the median function must take the element in the middle of the sorted array.

### CODE REVIEW

**Comment by ebadi** [comment]
I propose using "selection algorithm" instead of the current algorithm that unnecessarily sorts all elements first.
http://en.wikipedia.org/wiki/Selection_algorithm

**Comment by ebadi** [comment]
It seems that the median function (in math) is implemented incorrectly as the function doesn’t even use the sorted array! (I fixed it just to show the correct implementation) . Any way I replaced it with QuickSelect method instead which is much faster than current method (unnecessarily sorting all elements to find the element in the middle).

For 3×3 median filter (image) I replaced it with hardwired median search described here :
http://users.utcluj.ro/~baruch/resources/Image/xl23_16.pdf

Codes are in public domain and are taken from here :
http://ndevilla.free.fr/median/median/

**Comment by 6thimage** [comment]
The fix for p_median is a duplicate of #85 and #96

**Comment by ebadi** [comment]
Counter exam for each fix is provided using Matlab code (I used FreeMat available here http://freemat.sourceforge.net/ ) 

image/conv2: returns incorrect values as it doesn't flip the kernel both in vertical and horizontal directions, I fixed this major problem and added support for rectangular kernels too.

dsp/conv : this function also doesn't work correctly as it returns an extra value in the beginning of the result and also uses uninitialised memory addresses (assumes this memory addresses are zero)

**Comment by ebadi** [comment]
See the new pull here : https://github.com/parallella/pal/pull/148

**Pull request closed without merging**
