### PR TITLE
Optimize p_box3x3_f32().

### PR DESCRIPTION
**Pull request by pfalcon**
Signed-off-by: Paul Sokolovsky <pfalcon@users.sourceforge.net>

### CODE REVIEW

**Comment by pfalcon** [comment]
Couple of notes:

1. I figured running "make check" in tests/image/ doesn't really recognize failures in individual tests (they're just reported as PASS). Kind suggestions: guys, if you want people contribute to "optimization" part of library, it's your job as maintainers to make infrastructure be right and comfortable (people can help with that, see #173, #174 from me, but overall, it's not much fun to go for "optimize" if basic thinsg like testing don't work).

2. The testcase could use some (hopefully minor) codestyle cleanup, feel free to request that, but let's see first if you'd appreciate this contribution at all.

Ah, almost forgot - this is my application for optimization crowdsourcing contest https://www.parallella.org/2015/06/02/write-one-c-function-and-get-a-free-computer/ ;-)

**Comment by pfalcon** [comment]
On x86_64, this optimization reduces both code size and stack usage.

**Comment by aolofsson** [comment]
Great! Looks good. Please sign off commit/pr.

Agree, regarding verification, it is being worked on! Although I would add that verification is everyone's responsibility if we want to scale.(especially adding invividual test cases)

**Comment by pfalcon** [comment]
> Great! Looks good. Please sign off commit/pr.

Both commits of this PR are signed-off. Remembering that github may use PR description as merge commit description, and you want even that merge commit signed off, I added it, hope that's what you meant.

> Agree, regarding verification, it is being worked on! Although I would add that verification is everyone's responsibility if we want to scale.(especially adding invividual test cases)

Sure, that's why I included a testcase in this PR - I wouldn't know if I implementation is correct w/o it. I meant ground testing infrastructure, like which unit test framework to use, helper routines, overall tets format, etc. - if each contributor would start to invent that stuff, it would be a mess. Anyway, seeing updates to check_p_rgb2greyscale.c in the same dir, I propagated them to test in this patch too, thansk for them.

Also made headlines of commit messages more consistent with existing.

**Pull request merged**
