### PR TITLE
math:p_stddev Refactoring to use existing functions

### PR DESCRIPTION
**Pull request by mateunho**
- use mean calculation from pal
- use sqrt calculation from pal

### CODE REVIEW

**Comment by HenryJia** [comment]
@mateunho 

My code is using the exact same mechanism as the existing functions. I think it might be a bad idea to make it call those functions because calling functions is slower than just directly running the code inside those functions. This could make a difference if the vectors being inputted are large enough.

**Comment by mateunho** [comment]
I do not know the exact mechanics (electronics) behind Epiphany, but you may be right. If you can, then please provide a reproducible code sample showing mentioned difference. Until then, I will stick to using predefined functions, since they are easier in future maintenance.

**Comment by HenryJia** [comment]
IF you compare my code with the code in the functions then they are the same. There is no difference.

**Comment by aolofsson** [comment]
@HenryJia @mateunho  Can you verify code to verify that this is bare metal code. Any call to GCC internal libs will cause the code size to blow up. One way to check this is to cross compile with the e-gcc compiler and look at assembly code. I am quite sure the '/' operator in code will be a problem.

**Comment by HenryJia** [comment]
@aolofsson 

Hmmm, I don't think it's physically possible to calculate mean or standard deviation without divide.

I'm going to try and implement a divide function through bitwise operations. Computationally, this should be quite fast and work on a parallela and other devices that don't have hardware divide functions.

**Comment by aolofsson** [comment]
Agree that in this case you can't remove the divide. This is something that needs to be handled by the compiler as efficiently as possible. A basic arithmetic primitive.  For reference, here is the assembly code produced by gcc for "/" operator....

800002b4 <___divsf3>:
800002b4:	975c 0701 	str r4,[sp],-0xe
800002b8:	9e0b 0042 	mov r4,0x4f0
800002bc:	d6dc 2401 	str lr,[sp,+0xd]
800002c0:	800b 1802 	movt r4,0x8000
800002c4:	155c 0400 	str r0,[sp,+0x2]
800002c8:	35dc 0400 	str r1,[sp,+0x3]
800002cc:	141b 0401 	add r0,sp,8
800002d0:	341b 0402 	add r1,sp,16
800002d4:	77dc 2401 	str fp,[sp,+0xf]
800002d8:	1152      	jalr r4
800002da:	341b 0404 	add r1,sp,32
800002de:	161b 0401 	add r0,sp,12
800002e2:	1152      	jalr r4
800002e4:	364c 0400 	ldr r1,[sp,+0x4]
800002e8:	04b3      	sub r0,r1,1
800002ea:	1220      	bgtu 8000030e <___divsf3+0x5a>
800002ec:	141b 0402 	add r0,sp,16
800002f0:	3c0b 0032 	mov r1,0x3e0
800002f4:	200b 1802 	movt r1,0x8000
800002f8:	0552      	jalr r1
800002fa:	77cc 2401 	ldr fp,[sp,+0xf]
800002fe:	974c 0401 	ldr r4,[sp,+0xe]
80000302:	d6cc 2401 	ldr lr,[sp,+0xd]
80000306:	b41b 2407 	add sp,sp,56
8000030a:	194f 0402 	rts
8000030e:	544c 0401 	ldr r2,[sp,+0x8]
80000312:	141b 0404 	add r0,sp,32
80000316:	68b3      	sub r3,r2,1
80000318:	ec40      	blteu 800002f0 <___divsf3+0x3c>
8000031a:	76cc 0400 	ldr r3,[sp,+0x5]
8000031e:	14cc 0401 	ldr r0,[sp,+0x9]
80000322:	0c0a      	eor r0,r3,r0
80000324:	16dc 0400 	str r0,[sp,+0x5]
80000328:	063b 4000 	sub r16,r1,4
8000032c:	0300      	beq 80000332 <___divsf3+0x7e>
8000032e:	0533      	sub r0,r1,2
80000330:	0810      	bne 80000340 <___divsf3+0x8c>
80000332:	1a0b 00b2 	mov r0,0xbd0
80000336:	653a      	sub r3,r1,r2
80000338:	000b 1802 	movt r0,0x8000
8000033c:	d810      	bne 800002ec <___divsf3+0x38>
8000033e:	d9e0      	b 800002f0 <___divsf3+0x3c>
80000340:	0a3b 4000 	sub r16,r2,4
80000344:	3000      	beq 800003a4 <___divsf3+0xf0>
80000346:	0933      	sub r0,r2,2
80000348:	3600      	beq 800003b4 <___divsf3+0x100>
8000034a:	574c 0400 	ldr r2,[sp,+0x6]
8000034e:	354c 0401 	ldr r1,[sp,+0xa]
80000352:	17cc 0400 	ldr r0,[sp,+0x7]
80000356:	75cc 0401 	ldr r3,[sp,+0xb]
8000035a:	28ba      	sub r1,r2,r1
8000035c:	375c 0400 	str r1,[sp,+0x6]
80000360:	41ba      	sub r2,r0,r3
80000362:	0530      	bgteu 8000036c <___divsf3+0xb8>
80000364:	2793      	add r1,r1,-1
80000366:	0036      	lsl r0,r0,0x1
80000368:	375c 0400 	str r1,[sp,+0x6]
8000036c:	400b 0002 	mov r2,0x0
80000370:	23e3      	mov r1,0x1f
80000372:	400b 1402 	movt r2,0x4000
80000376:	800b 2002 	mov r12,0x0
8000037a:	0c3f 400a 	sub r16,r3,r0
8000037e:	0420      	bgtu 80000386 <___divsf3+0xd2>
80000380:	917f 240a 	orr r12,r12,r2
80000384:	01ba      	sub r0,r0,r3
80000386:	4826      	lsr r2,r2,0x1
80000388:	0036      	lsl r0,r0,0x1
8000038a:	24b3      	sub r1,r1,1
8000038c:	f710      	bne 8000037a <___divsf3+0xc6>
8000038e:	2fe3      	mov r1,0x7f
80000390:	30df 040a 	and r1,r12,r1
80000394:	443b 0008 	sub r2,r1,64
80000398:	1400      	beq 800003c0 <___divsf3+0x10c>
8000039a:	141b 0402 	add r0,sp,16
8000039e:	97dc 2400 	str r12,[sp,+0x7]
800003a2:	a7e0      	b 800002f0 <___divsf3+0x3c>
800003a4:	0003      	mov r0,0x0
800003a6:	17dc 0400 	str r0,[sp,+0x7]
800003aa:	175c 0400 	str r0,[sp,+0x6]
800003ae:	141b 0402 	add r0,sp,16
800003b2:	9fe0      	b 800002f0 <___divsf3+0x3c>
800003b4:	0083      	mov r0,0x4
800003b6:	165c 0400 	str r0,[sp,+0x4]
800003ba:	141b 0402 	add r0,sp,16
800003be:	99e0      	b 800002f0 <___divsf3+0x3c>
800003c0:	731f 0406 	lsl r3,r12,0x18
800003c4:	eb80      	blt 8000039a <___divsf3+0xe6>
800003c6:	003b 4000 	sub r16,r0,0
800003ca:	e800      	beq 8000039a <___divsf3+0xe6>
800003cc:	100b 0ff2 	mov r0,0xff80
800003d0:	901b 2408 	add r12,r12,64
800003d4:	1feb 1ff2 	movt r0,0xffff
800003d8:	905f 240a 	and r12,r12,r0
800003dc:	dfe0      	b 8000039a <___divsf3+0xe6>
800003de:	01a2      	nop

800003e0 <___pack_f>:
800003e0:	4044      	ldr r2,[r0]
800003e2:	21c4      	ldr r1,[r0,0x3]
800003e4:	68b3      	sub r3,r2,1
800003e6:	60c4      	ldr r3,[r0,0x1]
800003e8:	4940      	blteu 8000047a <___pack_f+0x9a>
800003ea:	8a3b 2000 	sub r12,r2,4
800003ee:	4300      	beq 80000474 <___pack_f+0x94>
800003f0:	093b 4000 	sub r16,r2,2
800003f4:	2400      	beq 8000043c <___pack_f+0x5c>
800003f6:	4433      	sub r2,r1,0
800003f8:	2200      	beq 8000043c <___pack_f+0x5c>
800003fa:	4144      	ldr r2,[r0,0x2]
800003fc:	893b 20f0 	sub r12,r2,-126
80000400:	4980      	blt 80000492 <___pack_f+0xb2>
80000402:	0bbb 000f 	sub r0,r2,127
80000406:	3760      	bgt 80000474 <___pack_f+0x94>
80000408:	0fe3      	mov r0,0x7f
8000040a:	045a      	and r0,r1,r0
8000040c:	803b 2008 	sub r12,r0,64
80000410:	2300      	beq 80000456 <___pack_f+0x76>
80000412:	279b 0007 	add r1,r1,63
80000416:	0433      	sub r0,r1,0
80000418:	2a80      	blt 8000046c <___pack_f+0x8c>
8000041a:	4b9b 000f 	add r2,r2,127
8000041e:	2456      	lsl r1,r1,0x2
80000420:	4b16      	lsl r2,r2,0x18
80000422:	1feb 0ff2 	mov r0,0xffff
80000426:	2526      	lsr r1,r1,0x9
80000428:	4b06      	lsr r2,r2,0x18
8000042a:	0feb 1002 	movt r0,0x7f
8000042e:	4af6      	lsl r2,r2,0x17
80000430:	245a      	and r1,r1,r0
80000432:	6ff6      	lsl r3,r3,0x1f
80000434:	057a      	orr r0,r1,r2
80000436:	01fa      	orr r0,r0,r3
80000438:	194f 0402 	rts
8000043c:	4003      	mov r2,0x0
8000043e:	2003      	mov r1,0x0
80000440:	1feb 0ff2 	mov r0,0xffff
80000444:	0feb 1002 	movt r0,0x7f
80000448:	4af6      	lsl r2,r2,0x17
8000044a:	245a      	and r1,r1,r0
8000044c:	6ff6      	lsl r3,r3,0x1f
8000044e:	057a      	orr r0,r1,r2
80000450:	01fa      	orr r0,r0,r3
80000452:	194f 0402 	rts
80000456:	900b 2002 	mov r12,0x80
8000045a:	041b 0008 	add r0,r1,64
8000045e:	865f 208a 	and r12,r1,r12
80000462:	103b 4400 	sub r16,r12,0
80000466:	2012      	movne r1,r0
80000468:	0433      	sub r0,r1,0
8000046a:	d870      	bgte 8000041a <___pack_f+0x3a>
8000046c:	2426      	lsr r1,r1,0x1
8000046e:	481b 0010 	add r2,r2,128
80000472:	d6e0      	b 8000041e <___pack_f+0x3e>
80000474:	5fe3      	mov r2,0xff
80000476:	2003      	mov r1,0x0
80000478:	e4e0      	b 80000440 <___pack_f+0x60>
8000047a:	000b 0002 	mov r0,0x0
8000047e:	020b 1002 	movt r0,0x10
80000482:	247a      	orr r1,r1,r0
80000484:	1feb 0ff2 	mov r0,0xffff
80000488:	0feb 1002 	movt r0,0x7f
8000048c:	245a      	and r1,r1,r0
8000048e:	5fe3      	mov r2,0xff
80000490:	d8e0      	b 80000440 <___pack_f+0x60>
80000492:	104b 0ff2 	mov r0,0xff82
80000496:	1feb 1ff2 	movt r0,0xffff
8000049a:	413a      	sub r2,r0,r2
8000049c:	08bb 4003 	sub r16,r2,25
800004a0:	2360      	bgt 800004e6 <___pack_f+0x106>
800004a2:	802b 2002 	mov r12,0x1
800004a6:	112f 040a 	lsl r0,r12,r2
800004aa:	0393      	add r0,r0,-1
800004ac:	454a      	lsr r2,r1,r2
800004ae:	00da      	and r0,r0,r1
800004b0:	101f 0402 	movne r0,r12
800004b4:	017a      	orr r0,r0,r2
800004b6:	2fe3      	mov r1,0x7f
800004b8:	20da      	and r1,r0,r1
800004ba:	443b 0008 	sub r2,r1,64
800004be:	1510      	bne 800004e8 <___pack_f+0x108>
800004c0:	5003      	mov r2,0x80
800004c2:	415a      	and r2,r0,r2
800004c4:	201b 0008 	add r1,r0,64
800004c8:	883b 2000 	sub r12,r2,0
800004cc:	0412      	movne r0,r1
800004ce:	2056      	lsl r1,r0,0x2
800004d0:	5feb 0ff2 	mov r2,0xffff
800004d4:	5feb 13f2 	movt r2,0x3fff
800004d8:	2526      	lsr r1,r1,0x9
800004da:	013f 400a 	sub r16,r0,r2
800004de:	4003      	mov r2,0x0
800004e0:	0023      	mov r0,0x1
800004e2:	4022      	movgtu r2,r0
800004e4:	aee0      	b 80000440 <___pack_f+0x60>
800004e6:	0003      	mov r0,0x0
800004e8:	039b 0007 	add r0,r0,63
800004ec:	f1e0      	b 800004ce <___pack_f+0xee>
800004ee:	01a2      	nop

800004f0 <___unpack_f>:
800004f0:	0044      	ldr r0,[r0]
800004f2:	9feb 2ff2 	mov r12,0xffff
800004f6:	42e6      	lsr r2,r0,0x17
800004f8:	4b16      	lsl r2,r2,0x18
800004fa:	8feb 3002 	movt r12,0x7f
800004fe:	63e6      	lsr r3,r0,0x1f
80000500:	4b06      	lsr r2,r2,0x18
80000502:	105f 040a 	and r0,r12,r0
80000506:	64d4      	str r3,[r1,0x1]
80000508:	6833      	sub r3,r2,0
8000050a:	1910      	bne 8000053c <___unpack_f+0x4c>
8000050c:	003b 4000 	sub r16,r0,0
80000510:	2700      	beq 8000055e <___unpack_f+0x6e>
80000512:	502b 0ff2 	mov r2,0xff81
80000516:	9feb 2ff2 	mov r12,0xffff
8000051a:	6063      	mov r3,0x3
8000051c:	00f6      	lsl r0,r0,0x7
8000051e:	5feb 1ff2 	movt r2,0xffff
80000522:	9feb 33f2 	movt r12,0x3fff
80000526:	6454      	str r3,[r1]
80000528:	0036      	lsl r0,r0,0x1
8000052a:	68e2      	mov r3,r2
8000052c:	4b93      	add r2,r2,-1
8000052e:	023f 408a 	sub r16,r0,r12
80000532:	fb40      	blteu 80000528 <___unpack_f+0x38>
80000534:	6554      	str r3,[r1,0x2]
80000536:	05d4      	str r0,[r1,0x3]
80000538:	194f 0402 	rts
8000053c:	6bbb 001f 	sub r3,r2,255
80000540:	1300      	beq 80000566 <___unpack_f+0x76>
80000542:	600b 0002 	mov r3,0x0
80000546:	489b 00f0 	add r2,r2,-127
8000054a:	00f6      	lsl r0,r0,0x7
8000054c:	600b 1402 	movt r3,0x4000
80000550:	4554      	str r2,[r1,0x2]
80000552:	01fa      	orr r0,r0,r3
80000554:	4063      	mov r2,0x3
80000556:	4454      	str r2,[r1]
80000558:	05d4      	str r0,[r1,0x3]
8000055a:	194f 0402 	rts
8000055e:	0043      	mov r0,0x2
80000560:	0454      	str r0,[r1]
80000562:	194f 0402 	rts
80000566:	003b 4000 	sub r16,r0,0
8000056a:	0b00      	beq 80000580 <___unpack_f+0x90>
8000056c:	400b 0002 	mov r2,0x0
80000570:	420b 1002 	movt r2,0x10
80000574:	415a      	and r2,r0,r2
80000576:	f000      	beq 80000556 <___unpack_f+0x66>
80000578:	4023      	mov r2,0x1
8000057a:	4454      	str r2,[r1]
8000057c:	05d4      	str r0,[r1,0x3]
8000057e:	eee0      	b 8000055a <___unpack_f+0x6a>
80000580:	0083      	mov r0,0x4
80000582:	0454      	str r0,[r1]
80000584:	194f 0402 	rts

**Comment by olajep** [comment]
@aolofsson 
It seems to have to do with IEEE754 compatibility with NaN Infinity and ...
Compared with clang  divsf3 implementation total size 796 vs. (664-720) for gcc's implementation.
Interlisted disassembly/source:
https://gist.github.com/olajep/102e1b0a2ce3d38b834c

```
e-gcc -funsafe-math-optimizations
```
seems to work if you don't care about full IEEE-754 compatibility

**Pull request closed without merging**
