### PR TITLE
Implemented somewhat naive scharr operator

### PR DESCRIPTION
**Pull request by damjandakic**

### CODE REVIEW

**Comment by aolofsson** [comment]
Nice! 
-How is the performance?
-Same hypot inline function as in sobel. Does it make sense to move to a some kind of common file?

**Comment by damjandakic** [comment]
Yeah, the hypot function should be moved into a common file but as I am new to the project and I don't see any header files being used in that part of the source, I left it like this and hope someone "older" will refactor it with respect to the project guidelines?

**Comment by damjandakic** [comment]
Btw, not sure where else to ask, but are we supposed to use SSE and/or Neon instructions?
Thanks

**Comment by aolofsson** [comment]
If this is a must to reach good performance (ie >40% of peak) on intel arm, then yes. Open to suggestions as to the best file structure for getting this done. Planning a reorg for next week.
Options:
-ifdefs in code
-a set of inline functions to implement for each architecture, resolved at build time
-other??

**Pull request merged**
