### PR TITLE
math: p_floor: Implement floor function

### PR DESCRIPTION
**Pull request by Adamszk**
commited from Git website

### CODE REVIEW

**Comment by mateunho** [comment]
You've mixed `p_erf()` and `p_floor()` implementations one within PR.

**Comment by Adamszk** [comment]
@mateunho 
Thanks for comments.  This one is really a messy job.  I created a new branch through the web not remotely.  Lesson learned.  I will created a new branch remotely and redo again.  This one will be removed.  Unless you have some tricks.  Meanwhile I like to comment that git gui is a very useful tool.  It helps a lot.

**Comment by mateunho** [comment]
I've checked out your current repo state and run:
- `git rebase -i 6fe1782`, here you pick only the one on top and squash rest of them (like [here](https://gist.github.com/mateunho/d9e9b898f848b70dc0f4#file-gistfile1-txt)). _If you don't get past this command successfully, then abort following_
- `git branch tmp`
- `git reset --hard 0c385c7`
- `git cherry-pick refs/heads/tmp`
- `git branch -D tmp`
- `git push -f origin devel2`

those commands seems to make the deal

**Comment by Adamszk** [comment]
@mateunho 
I think I screw things up even further.  devel2 branch was not created locally because I made floor commit on the web.(remotely) So I created locally but did not do any further.  then follow the above steps and something did not go through.
git branch
* (no branch, rebasing devel2)
  devel
  devel2
  devel3
  master
 git checkout devel
src/math/p_add.c: needs merge
error: you need to resolve your current index first

**Pull request closed without merging**
