### PR TITLE
Improve p_median performance and add p_find_kth_f32

### PR DESCRIPTION
**Pull request by lbguilherme**
Previously it did a full sort of the input vector taking `O(n log n)`. Now it will use the select/median of medians algorithm to find only the element it cares about. Now takes `O(n)`, a linear time. This improves performance when dealing with large vectors.

### CODE REVIEW

**Comment by blitmap** [comment]
This looks good but the original is avoiding division - change the "/ 2"s back to >> 1 and it'd be better :-)

Good on you for changing the "% 2" to "& 1" in the condition though.

**Comment by lbguilherme** [comment]
@blitmap As they are integers any sane compiler will optimize a power-of-two division/multiplication/modulus to a shift/and operation. This is a too trivial optimization for a programmer to care about. Anyway, I can make the change.

**Comment by blitmap** [comment]
Another thought about p_median():

You could assign the first median (*c) and then if the vector is odd in length, add the 2nd number and (again) multiply by .5.  Calling find_kth seems unnecessary as copy is already sorted from the first invocation?

Something like this:

```c
p_find_kth_f32(copy, c, n, n >> 1, p, team);

if (n ^ 1)
{
    *c += copy[(n >> 1) + 1];
    *c *= 0.5;
}
```

I believe this would be correct - what do you think?

**Comment by lbguilherme** [comment]
Actually `find_kth` doesn't sort the input vector. It does just enough to figure out where the k-th would be and return it. So, we can't retrieve the element after it, two calls are indeed required.

One interesting thing thought is that 2*O(n) is still better than 1*O(n log n). So, it will be still faster than a full sort.

**Comment by blitmap** [comment]
Oh I think I get it now - well done :-)

**Comment by ebadi** [comment]
p_find_kth_f32 is a useful function, but normal median can be implemented in a better way:
* without calling the function twice 
* without using recursion

https://github.com/parallella/pal/blob/7d2b18448a9d5bb38443c45d570769224db7041f/src/math/p_median.c

So I assume it is fully tested, as I took it from a reliable source:
http://ndevilla.free.fr/median/median/

**Comment by WesleyCeraso** [comment]
I've already done this, the current implementation already uses QuickSelect

**Comment by lbguilherme** [comment]
I have created a new pull request removing my changes do `p_median` as it is already done. Now only `p_find_kth_f32` is included as it may be useful for other purposes.

See #107.

Thanks for the feedback!

**Pull request closed without merging**
