### PR TITLE
Add p_median to math library (with simple example)

### PR DESCRIPTION
**Pull request by 6thimage**
Issue reference: #54

Signed-off-by: Ian Griffiths <6thimage@gmail.com>

### CODE REVIEW

**Comment by aolofsson** [comment]
Thanks! No division in code please (I will add to general guidlines)

**Comment by 6thimage** [comment]
The n/2 can easily be changed into bit shifts, but the division of the sum (src/math/p_median.c:30) is unavoidable - as it is part of the algorithm. Additionally it cannot be changed into a bit shift as it a floating point.

**Comment by aolofsson** [comment]
But /2 can be converted to *0.5 right?

**Comment by 6thimage** [comment]
As it is a floating point operation, /2. and *0.5 are the same (performance wise) from my understanding. For integer mathematics, I understand that a bit shift can be significantly faster than multiplication and division on some architectures.

**Comment by mateunho** [comment]
For Epiphany /2 and *0.5 are not the same though.

**Comment by 6thimage** [comment]
@mateunho is that so - I had assumed that they would be. I'll push a commit changing it then.

**Pull request merged**
